---
title: Adam Catangui
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
nav:
  Performances: "/performances"
  Repertoire: "/repertoire"
  Contact: "/contact"
bio: I am a classical singer from Sioux Falls, SD. Currently in my senior year at
  O'Gorman High School and planning to do further study in Voice and Opera.
email: adamcatangui@gmail.com
description: This is online portfolio of Adam Catangui.
baseurl: 
markdown: kramdown
