---
title: Adam Catangui
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
nav:
  Performances: "/performances"
  Repertoire: "/repertoire"
  Contact: mailto:adamcatangui@gmail.com
bio: "TENOR\n\nIt has been my childhood dream to become an opera singer. \n\n* Eastman
  School of Music ‘23\n* Chautauqua Institution Voice Program 2019\n* YoungArts Winner
  2019\n"
email: adamcatangui@gmail.com
description: This is online portfolio of Adam Catangui.
baseurl: 
markdown: kramdown
